--- # Testing the J2 Template Module
- hosts: lab1:lab2
  vars:
    userName: test
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=test.conf.j2 dest=/home/ansible/test.conf owner=ansible group=ansible mode=750
